id: P803A2704
initial_creation_type: input
source_metadata:
  title: Nonsectarianism Series
  language: zh
  description: 'Texts on the theme of nonsectarianism, impartiality or the absence
    of sectarian bias, a central ideal of the so-called nonsectarian or rimé (ris
    med) movement that blossomed in nineteenth-century Kham:'
  volume:
    f2f549a4c4ca4706a9fa8f8d69a3697d:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    8219eea3c6d54bb49a3d2d60a06c4ee9:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    f1628c6c88dc429aa798d27a5a867992:
      title: A Sun to Banish the Darkness of Wrong Views
      parent: Advice
    3d3b0711e3454028bfc0cb188cb5db3d:
      title: 'Opening the Door of Dharma: A Brief Discourse on the Essence of All
        Vehicles'
      parent: Advice
    85c7a81311fd48bd8520adf4076d9320:
      title: Satirical Advice for the Four Schools
      parent: Advice
    f947adeb449840deb7d59b345f14a19b:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    efc4188a327647c58363d0d44c6a085d:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Aspiration Prayers
    b590e962c76c41ed8fbbab33523ef7f7:
      title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
        of the Eight Great Chariots of the Practice Lineage'
      parent: Aspiration Prayers
    2fa28603e5794af3ad8ffcc3a509584b:
      title: Aspiration for the Spread of the Teachings
      parent: Aspiration Prayers
    64fc78ea666f4aac80921e7113a6d668:
      title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
      parent: Aspiration Prayers
    d2b70e1d1a9f442590cab7cddbf6597f:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Aspiration Prayers
    666fed4bcb9545f696a3dc670b2683d3:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    19875b2dc6ee4c42bde5e2be4821a915:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    e0164503a6a24d3a84c039eecac8c303:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    7f9a842590054e4b876aeb6c34b0aa1d:
      title: 'The Treasury of Blessings: A Prayer to Recall the Sublime Masters who
        Showed Great Kindness to the Land of Snows'
      parent: Prayers
    0bef5fc0909d468ba6fb8ff86d73175d:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Prayers
    b5622fc29d4941f2a263c91e52fd28da:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Prayers
    13fe21b2b8b144ab8c28fa85ed573715:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: Songs
created_at: '2022-03-01T04:51:37.223538'
last_modified_at: '2022-03-01T04:51:37.223540'
